[alias]
rel = "build --release --target=x86_64-unknown-linux-musl"
zig = "zigbuild --release --target=x86_64-unknown-linux-musl"

[target.x86_64-unknown-linux-musl]
rustflags = "-Ctarget-feature=+crt-static"
