name: Rust

on:
  push:
    branches: [main]
    tags: ["[0-9]+.[0-9]+.[0-9]+"]
  pull_request:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - dist
    steps:
      - uses: actions/checkout@v4
      - name: Get Cargo Version
        id: query-version
        run: |
          rustup target add x86_64-unknown-linux-musl
          cargo metadata --no-deps --format-version=1 \
          | jq -r 'first(.packages[]).version' \
          | xargs -0 printf "version=%s" \
          >> "$GITHUB_OUTPUT"
      - name: Check Tag
        id: check-tag
        run: |
          if git show-ref --tags --verify --quiet "refs/tags/${{steps.query-version.outputs.version}}"; then
            echo "tag=1" >> "$GITHUB_OUTPUT"
          else
            echo "tag=0" >> "$GITHUB_OUTPUT"
          fi
      - name: Extract Changelog for ${{steps.query-version.outputs.version}}
        id: query-changelog
        uses: release-flow/keep-a-changelog-action@v3
        with:
          command: query
          version: ${{steps.query-version.outputs.version}}
      - uses: actions/download-artifact@v4
        with:
          path: "./dist"
          pattern: "rw-*"
      - name: Update Release
        uses: softprops/action-gh-release@v2
        if: ${{startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/main')}}
        with:
          name: "Version ${{steps.query-version.outputs.version}}"
          body: ${{steps.query-changelog.outputs.release-notes}}
          files: "./dist/**/rw-*"
          fail_on_unmatched_files: true
          prerelease: ${{contains(steps.query-version.outputs.version, '-')}}
          draft: ${{steps.check-tag.outputs.tag == 0 && !startsWith(github.ref, 'refs/tags/')}}
          make_latest: ${{!contains(steps.query-version.outputs.version, '-') && startsWith(github.ref, 'refs/tags/')}}
